### ISSUE TITLE
Allow downloading only X latest versions

### ISSUE THREAD

**Issue by rothshahar** [davglass/registry-static#1]
The fact that it takes 117GB to download the entire registry is limiting.
It's very likely that you'd only need one of the latest X versions of each package.
Would be nice to be able to specify how many to download. It should cut down the download size significantly. Could fallback on the remote registry if a really old version is needed?

**Comment by davglass** [comment]
We could add docs on the config to show that you can use `@try_files` first, then `rewrite` to the registry. That should keep us from having to setup an http server since one is already there.

**Comment by beaugunderson** [comment]
Currently at 95% and I'm at 157gb :)

But there's another issue with only grabbing the latest x versions, and it's that you can't account for the modules you want relying on only those latest x versions... Though figuring out only the latest of each version string actually depended on would be a fun exercise!

**Comment by bengl** [comment]
If you're taking this approach, you're still going to need to operate as a caching proxy, due to random modules requiring old stuff. For that reason, you might be better off using an actual caching proxy, like [sinopia](https://www.npmjs.com/package/sinopia).
