### ISSUE TITLE
lib/sync.js enhancements

### ISSUE THREAD

**Issue by davglass** [davglass/registry-static#15]
I was going to start the tests for this, but then I remembered that the sync script doesn't do everything that it should do.

The idea was that it scans the directory tree, grabs the latest `index.json` and then queries the registry to see if we have the latest version stored.

What it doesn't do that it should do:

  * sync any versions that are out of date
  * then verify all of the tarballs, pulling ones that are missing.

**Comment by bengl** [comment]
`lib/sync.js` is now gone, so closing this.
