### ISSUE TITLE
use abstract-blob-store

### ISSUE THREAD

**Issue by jbenet** [davglass/registry-static#26]
@mafintosh and @maxogden made https://www.npmjs.com/package/abstract-blob-store which is like the leveldown concept but for blobs.

it would be great to have registry-static use [abstract-blob-store](https://www.npmjs.com/package/abstract-blob-store) to have swappable backends. it could default to [fs-blob-store](https://www.npmjs.com/package/fs-blob-store) and thus not change the interface at all.

**Comment by bengl** [comment]
:+1:

Depending on use-cases, could even make a custom blob-store to put tarballs in one place and metadata elsewhere.

**Comment by davglass** [comment]
:+1:

**Comment by jbenet** [comment]
:+1: :clap: :smile:
