### ISSUE TITLE
index.json module causes error

### ISSUE THREAD

**Issue by lstoll** [davglass/registry-static#43]
There's a module named [index.json](https://www.npmjs.com/package/index.json) that causes a directory to be created called index.json, which conflicts with the index.json file.

For my purposes I just manually incremented the sequence file to skip it, but I thought it was worth noting.

**Comment by davglass** [comment]
Yup, I think @bengl ran into this too.

**Comment by bengl** [comment]
I did. This one's a tough one. For completion's sake, we ought to *not* skip the package called `index.json`. The only real solution will probably be to toss our meta `index.json` into the `/-/` namespace to avoid the collision. This means everyone will have to change their nginx configs to point there instead, which is going to require a major semver update to `registry-static`. :(

**Comment by evilpacket** [comment]
I just ran into this as well
```
2015-09-13T00:40:23.612Z static [info] [1] downloading http://registry.npmjs.org/index.json/-/index.json-1.0.0.tgz
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: ENOTDIR, mkdir '/Volumes/source/registry/index.json/-'
    at Error (native)
```

**Comment by bengl** [comment]
Until I fix this (which should be very shortly, I swear!) anyone running into this should simply restart their `registry-static` after adding 1 to the sequence in `/tmp/registry-static.seq` (or wherever your sequence file is).
