### ISSUE TITLE
Package called index.json

### ISSUE THREAD

**Issue by rvagg** [davglass/registry-static#52]
This is an interesting problem. I guess we need to completely ignore this package? It doesn't look like anything usable anyway.

```
2015-12-18T10:31:03.071Z static [info] [223479/571128] processing index.json
2015-12-18T10:31:03.080Z static [info] [1] downloading http://registry.npmjs.org/index.json/-/index.json-1.0.0.tgz
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: ENOTDIR: not a directory, mkdir '/mnt/npm/data/index.json/-'
    at Error (native)
```

**Comment by drewfish** [comment]
I seem to remember that we skipped this one. In theory it's a completely valid package name, but like you noticed it's not that useful in practice.

**Comment by davglass** [comment]
I think @bengl was thinking that we will move the default pages (`404.json` & `index.json`) under `/-/` and then update the `nginx.conf` to look there for them instead. That way we don't put any of our files in the root.

**Comment by bengl** [comment]
Yup. I did that here https://github.com/davglass/registry-static/commit/b36e069726908da339ca7b4a1adda981fbe9cac6

**Comment by rvagg** [comment]
ok, so it must just be my problem for not removing them in my old mirror
