### ISSUE TITLE
scoped packages

### ISSUE THREAD

**Issue by bengl** [davglass/registry-static#55]
Support for scoped packages is needed, as some popular non-scoped packages are starting to include scoped packages as dependencies. It's high-time to start treating scoped packages as first-class citizens, when we know about them.

But how do we know about them? The skimdb feed currently doesn't include scoped packages. On npm's IRC, @othiym23 suggested grabbing the dependencies on each change and adding any scoped packages to the queue for syncing. While this doesn't bring in brand new scoped packages, it does help prevent broken builds due to missing packages, so I think this is probably the way to go for now.

Opinions?

**Comment by davglass** [comment]
For now let's just mirror scoped packages that end up as a direct dependency of something we are already mirroring until the replication feed can be fixed/updated.

**Comment by bengl** [comment]
done for now.
