### ISSUE TITLE
Cannot read property dependencies of undefined

### ISSUE THREAD

**Issue by jlamendo** [davglass/registry-static#60]
I encountered a situation where after all of the checks here, ver.json, and therefore json, was undefined, causing an error [here](https://github.com/davglass/registry-static/blob/master/lib/index.js#L155-L168).

```javascript
    data.versions.forEach(function(ver){
        if (ver && ver.json && ver.json.version === latestVersion) {
            json = ver.json;
        }
    });
    if (!json) {
        return callback();
    }
    [
        'dependencies',
        'devDependencies',
        'optionalDependencies'
    ].forEach(function(depType) {
        if (typeof json[depType] !== 'object') {
```

I resolved it by modifying [index.js](https://github.com/davglass/registry-static/blob/master/lib/index.js#L155-L168) to:

```javascript
    data.versions.forEach(function(ver){
        if (ver && ver.json && typeof ver.json === 'object' && ver.json.version === latestVersion) {
            json = ver.json;
        }
    });
    if (!json) {
        return callback();
    }
    [
        'dependencies',
        'devDependencies',
        'optionalDependencies'
    ].forEach(function(depType) {
        if (!json || typeof json !=== 'object' || typeof json[depType] !== 'object') {
```

But I'm not certain that's the most ideal way to go about resolving this, as I didn't have time to investigate the root cause.

**Comment by bengl** [comment]
I think I fixed this in a fairly recent commit. If you run the latest from github source, it should have this in it. I'll publish a new version to npm soon.

**Comment by bengl** [comment]
@jlamendo can you confirm that latest `registry-static` is fixed?

**Comment by jlamendo** [comment]
@bengl Yep - working for me. Thanks!
