### ISSUE TITLE
Q: What is the complete purpose of the /-/index.json 

### ISSUE THREAD

**Issue by diasdavid** [davglass/registry-static#62]
The constant reading and writing of the /-/index.json file is creating some speed bottlenecks (or sometimes deadlocks) when adding modules to IPFS (because we get several threads trying to write to the same file in the go land), I was checking, and for npm to work, this file is not needed, but I'm not sure what was the full purpose of having this log, was it for internal monitoring tools to grab stats?

https://github.com/davglass/registry-static/blob/master/lib/index.js#L47-L84

//cc @bengl

**Comment by drewfish** [comment]
Yeah it aids monitoring. The difference between `seq` and `lastestSeq` is how far behind (in terms of package updates) it is.

**Comment by diasdavid** [comment]
Thank you @drewfish :)
