### ISSUE TITLE
Moar Tests!

### ISSUE THREAD

**Issue by davglass** [davglass/registry-static#9]
Always add tests...

**Comment by bengl** [comment]
Claiming the following:

* hooks.js
* files.js
* util.js
* background.js

**Comment by davglass** [comment]
Starting on `lib/logger.js`

**Comment by davglass** [comment]
I'm adding placeholders for all files under `./lib` so that we get an estimate on what needs to be done.

**Comment by davglass** [comment]
I pushed the logger tests, upgraded vows and instanbul to their latest and removed `./lib/clone` as it was a bad idea and just a test.

Starting on `lib/index.js` now.

**Comment by davglass** [comment]
Added tests for `lib/check/js`

**Comment by bengl** [comment]
Closing since the coverage is pretty good now.
